Keep the AsyncMultiMap cache in sync even after split-brains
kiwigrid/vert.x pull request #14
Opened 2016-10-12 15:50 UTC by Andy2003

Keep the AsyncMultiMap cache in sync even after split-brains
**does not solve merge conflicts of MultiMap itself**

2016-10-12 16:18 UTC, mirkoseifert approved these changes
From my point of view, the changes look fine.

2016-10-12 16:39 UTC, jekkel requested changes
Looks good overall - only a test for the changed behaviour should be added.

2016-10-12 16:39 UTC, jekkel commented on vertx-hazelcast/src/test/java/org/vertx/java/spi/cluster/impl/hazelcast/HazelcastAsyncMultiMapTest.java
> +public class HazelcastAsyncMultiMapTest {
It seems you're only testing that hz multimap does not merge "correctly". Shouldn't you test for the clearance of the cache, should you? I thought clearing the cache is what this PR is all about.

2016-10-12 16:39 UTC, jekkel commented on vertx-hazelcast/src/main/java/org/vertx/java/spi/cluster/impl/hazelcast/HazelcastAsyncMultiMap.java
> -        // remove directly from cache as well, b/c if the hazelcast does know the server id , it will never get thrown
I feel a lot better with this going out again. This is what we added a version before, right?

2016-10-13 10:11 UTC, Andy2003 commented on vertx-hazelcast/src/main/java/org/vertx/java/spi/cluster/impl/hazelcast/HazelcastAsyncMultiMap.java
> -        // remove directly from cache as well, b/c if the hazelcast does know the server id , it will never get thrown
yes

2016-10-13 11:13 UTC, Andy2003 commented on vertx-hazelcast/src/test/java/org/vertx/java/spi/cluster/impl/hazelcast/HazelcastAsyncMultiMapTest.java
> +public class HazelcastAsyncMultiMapTest {
I tested the changed behaviour: if you remove the LifeCycleListener the test will fail. I just test that we get the same values which are stored in the cluster.

2016-10-13 11:17 UTC, merged